baseURL = "https://pacificnwsacredharpsingers.netlify.app/"
languageCode = "en-us"
title = "Pacific Northwest Sacred Harp Singers"
theme = "base"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  description = "Sacred Harp Singing in the Pacific Northwest."
  title = "Pacific Northwest Sacred Harp Singers"
  shortTitle = "PCNWSHS"
  contactEmail = "PNWSHS@PacificNWsacredharpsingers.org"
  headerImage  = "images/header.png"
  author = "Tough Pixels"
  imageSizes = "1280 768 640 320"
  imageFormats = "webp jpeg"
